startup_project/startup_con/blogs/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.BlogListView.as_view(), name='blogs'),
    path('<slug:category_slug>/<int:blog_id>', views.blog_detail, name='blog_detail'),
    path('categories/<slug:category_slug>', views.category_list , name='blogs_by_category'),
    path('search/', views.search, name='search')
]

startup_project/startup_con/pages/urls.py
from django.urls import path
from . import views
from pages.views import AboutView, IndexView ,ContactView

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about', AboutView.as_view(), name='about'),
    path( 'service' , views.service, name='service'),
    path( 'contact' , ContactView.as_view(), name='contact'),
]

startup_project/startup_con/startup/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('team/', include('team.urls')),
    path('testimonials/', include('testimonials.urls')),
    path('blogs/', include('blogs.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

startup_project/startup_con/team/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.team, name='team'),
]

startup_project/startup_con/testimonials/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.testimonials, name='testimonials'),
]

startup_project/startup_con/blogs/models.py
from django.db import models
from ckeditor.fields import RichTextField

# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=200,unique=True)
    slug = models.SlugField(max_length=200,unique=True)

    def __str__(self):
        return self.name

class Blog(models.Model):
    name = models.CharField(max_length=200,unique=True)
    category = models.ForeignKey(Category,null=True,on_delete=models.DO_NOTHING)
    description = RichTextField()
    image = models.ImageField(upload_to='blogs/%Y/%m/%d/',blank=True,null=True)
    date = models.DateTimeField(auto_now_add=True)
    available = models.BooleanField(default=True)

    class Meta:
        ordering = ['-date']

    def __str__(self):
        return self.name

startup_project/startup_con/pages/models.py
from django.db import models

# Create your models here.

class Contact(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    email = models.EmailField(max_length=100,blank=True,null=True)
    phone = models.CharField(max_length=100,blank=True,null=True)
    message = models.TextField(blank=True,null=True)

    def __str__(self):
        return self.email

startup_project/startup_con/team/models.py
from codecs import unicode_escape_decode
from enum import unique
from turtle import position
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Team(models.Model):
    name = models.CharField(max_length=100,)
    position = models.CharField(max_length=100)
    image = models.ImageField(upload_to='team/%Y/%m/%d/')
    avaiable = models.BooleanField(default=True)

    def __str__(self):
        return self.name

class SocMedia(models.Model):
    name = models.CharField(max_length=100)
    icon = models.ImageField(upload_to='socmedia/%Y/%m/%d/', blank=True, null=True)
    link = models.URLField(max_length = 200)
    team = models.ForeignKey(Team, on_delete=models.CASCADE)

    def __str__(self):
        return self.name

startup_project/startup_con/testimonials/models.py
from django.db import models

# Create your models here.

class Testimonial(models.Model):
    name = models.CharField(max_length=100)
    profession = models.CharField(max_length=100)
    image = models.ImageField(upload_to='testimonial/%Y/%m/%d/')
    description = models.TextField()
    avaiable = models.BooleanField(default=True)

    def __str__(self):
        return self.name

startup_project/startup_con/pages/forms.py
from dataclasses import fields
from email import message
from django import forms
from .models import Contact

class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs.update({'class': 'form-control','placeholder':'Enter your first name'})
        self.fields['email'].widget.attrs.update({'class': 'form-control','placeholder':'Enter your email'})
        self.fields['phone'].widget.attrs.update({'class': 'form-control','placeholder':'Enter your phone'})
        self.fields['message'].widget.attrs.update({'class': 'form-control','placeholder':'Enter your Message'})

    

    

startup_project/startup_con/blogs/views.py
from django.shortcuts import render
from .models import Blog, Category
from django.views.generic import ListView

from django.conf import settings





class BlogListView(ListView):
    model = Blog
    template_name = 'blogs.html'
    context_object_name = 'blogs'
    paginate_by = 2

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

def blog_detail(request, category_slug , blog_id):
    blog = Blog.objects.get(category__slug=category_slug, id=blog_id)
    categories = Category.objects.all()
   
    context = {
        'blog': blog,
        'categories': categories,
        }
        
    
    return render(request, 'blog_detail.html', context)

def category_list(request, category_slug):
    blogs = Blog.objects.all().filter(category__slug = category_slug)
    categories = Category.objects.all()
    context = {
        
        'blogs': blogs,
        'categories': categories
    }
    return render(request, 'blogs.html', context)

def search(request):
    blogs = Blog.objects.filter(name__contains = request.GET['search'])
    categories = Category.objects.all()
    context = {
        'blogs': blogs,
        'categories': categories
    }
    return render(request, 'blogs.html', context)

startup_project/startup_con/pages/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView 
from django.views.generic.edit import FormView
from testimonials.models import Testimonial
from team.models import Team, SocMedia
from blogs.models import Blog
from .forms import ContactForm
from django.urls import reverse_lazy
from django.contrib.messages.views import SuccessMessageMixin

# Create your views here.

class IndexView(ListView):
    template_name = 'index.html'
    model = Blog
    context_object_name = 'blogs'
    paginate_by = 3

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['testimonials'] = Testimonial.objects.all()
        context['teams'] = Team.objects.all()
        context['socmedia'] = SocMedia.objects.all()
        return context


class AboutView(TemplateView):
    template_name = 'about.html'

def service(request):
    return render(request, 'service.html')

class ContactView(SuccessMessageMixin,FormView):
    template_name = 'contact.html'
    form_class = ContactForm
    success_url = reverse_lazy('contact')
    success_message = 'Your message has been sent successfully'

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


    

startup_project/startup_con/team/views.py
from django.shortcuts import render
from .models import Team,SocMedia
from django.views.generic import ListView


# Create your views here.
def team(request):
    team = Team.objects.all()
    socmed = SocMedia.objects.all()
    context = {
        'team': team,
        'socmed': socmed,
    }
    return render(request, 'team.html', context)




    

    

startup_project/startup_con/testimonials/views.py
from django.shortcuts import render
from .models import Testimonial
# Create your views here.

def testimonials(request):
    testimonials = Testimonial.objects.all()
    context = {
        'testimonials': testimonials
    }
    return render(request, 'testimonials.html', context)

startup_project/startup_con/templates/about.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block content %}
    <!-- About Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-7">
                    <div class="section-title position-relative pb-3 mb-5">
                        <h5 class="fw-bold text-primary text-uppercase">About Us</h5>
                        <h1 class="mb-0">The Best IT Solution With 10 Years of Experience</h1>
                    </div>
                    <p class="mb-4">Tempor erat elitr rebum at clita. Diam dolor diam ipsum et tempor sit. Aliqu diam amet diam et eos labore. Clita erat ipsum et lorem et sit, sed stet no labore lorem sit. Sanctus clita duo justo et tempor eirmod magna dolore erat amet</p>
                    <div class="row g-0 mb-3">
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.2s">
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Award Winning</h5>
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Professional Staff</h5>
                        </div>
                        <div class="col-sm-6 wow zoomIn" data-wow-delay="0.4s">
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>24/7 Support</h5>
                            <h5 class="mb-3"><i class="fa fa-check text-primary me-3"></i>Fair Prices</h5>
                        </div>
                    </div>
                    <div class="d-flex align-items-center mb-4 wow fadeIn" data-wow-delay="0.6s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Call to ask any question</h5>
                            <h4 class="text-primary mb-0">+012 345 6789</h4>
                        </div>
                    </div>
                    <a href="{% url 'contact' %}" class="btn btn-primary py-3 px-5 mt-3 wow zoomIn" data-wow-delay="0.9s">Contact</a>
                </div>
                <div class="col-lg-5" style="min-height: 500px;">
                    <div class="position-relative h-100">
                        <img class="position-absolute w-100 h-100 rounded wow zoomIn" data-wow-delay="0.9s" src="{% static 'img/about.jpg' %}" style="object-fit: cover;">
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- About End -->

{% endblock %}

startup_project/startup_con/templates/blog_detail.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block content %}
    <!-- Blog Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <div class="col-lg-8">
                    <!-- Blog Detail Start -->
                    <div class="mb-5">
                        <img class="img-fluid w-100 rounded mb-5" src="{{blog.image.url}}" alt="">
                        <h1 class="mb-4">{{blog.name}}</h1>
                        <p>{{blog.description|safe}}</p>
                    </div>
                    <!-- Blog Detail End -->
                </div>
    
                <!-- Sidebar Start -->
                <div class="col-lg-4">
    
                    <!-- Category Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Categories</h3>
                        </div>
                        <div class="link-animated d-flex flex-column justify-content-start">
                            {% for category in categories %}
                            <a class="h5 fw-semi-bold bg-light rounded py-2 px-3 mb-2" href="{% url  'blogs_by_category' category.slug %}"><i class="bi bi-arrow-right me-2"></i>{{category.name}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Category End -->
                </div>
                <!-- Sidebar End -->
            </div>
        </div>
    </div>
    <!-- Blog End -->


{% endblock %}

startup_project/startup_con/templates/blogs.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block content %}
    <!-- Blog Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="row g-5">
                <!-- Blog list Start -->
                <div class="col-lg-8">
                    <div class="row g-5">
                        {% for blog in blogs %}
                        <div class="col-md-6 wow slideInUp" data-wow-delay="0.1s">
                            <div class="blog-item bg-light rounded overflow-hidden">
                                <div class="blog-img position-relative overflow-hidden">
                                    <img class="img-fluid" src="{{blog.image.url}}" alt="">
                                </div>
                                <div class="p-4">
                                    <div class="d-flex mb-3">
                                        <small><i class="far fa-calendar-alt text-primary me-2"></i>{{blog.date}}</small>
                                    </div>
                                    <h4 class="mb-3">{{blog.name}}</h4>
                                    <p>{{blog.description|truncatechars:35|safe}}</p>
                                    <a class="text-uppercase" href="{% url 'blog_detail' blog.category.slug blog.id %}">Read More <i class="bi bi-arrow-right"></i></a>
                                </div>
                            </div>
                        </div>
                        {% endfor %}
                        <div class="clearfix">
                            {% if is_paginated %}
                    
                                {% if page_obj.number == 1 %}
                                    <a class="btn btn-outline-info float-right" href="?page=2">Older Posts &rarr;</a>
                                {% endif %}
                    
                                {% if page_obj.has_previous %}
                                    <a class="btn btn-outline-info" href="?page={{ page_obj.previous_page_number }}">Previous &lsaquo;</a>
                                {% endif %}
                    
                                {% if page_obj.has_next and page_obj.number != 1 %}
                                    <a class="btn btn-outline-info float-right" href="?page={{ page_obj.next_page_number }}">Next&rsaquo;</a>
                                {% endif %}
                    
                    
                            {% endif %}
                    
                    
                        </div>
                    </div>
                </div>
                <!-- Blog list End -->
    
                <!-- Sidebar Start -->
                <div class="col-lg-4">
                    <!-- Search Form Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <form method="GET" action="{% url 'search' %}">
                            <div class="input-group">
                                <input type="text" class="form-control p-3" placeholder="Keyword" name="search">
                                
                                <button class="btn btn-primary px-4"><i class="bi bi-search"></i></button>
                            </div>
                        
                    </div>
                    <!-- Search Form End -->
    
                    <!-- Category Start -->
                    <div class="mb-5 wow slideInUp" data-wow-delay="0.1s">
                        <div class="section-title section-title-sm position-relative pb-3 mb-4">
                            <h3 class="mb-0">Categories</h3>
                        </div>
                        <div class="link-animated d-flex flex-column justify-content-start">
                            {% for category in categories %}
                            <a class="h5 fw-semi-bold bg-light rounded py-2 px-3 mb-2" href="{% url  'blogs_by_category' category.slug %}"><i class="bi bi-arrow-right me-2"></i>{{category.name}}</a>
                            {% endfor %}
                        </div>
                    </div>
                    <!-- Category End -->

                </div>
                <!-- Sidebar End -->
            </div>
        </div>
    </div>
    <!-- Blog End -->


{% endblock %}

startup_project/startup_con/templates/contact.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block content %}


    <!-- Contact Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
                <h5 class="fw-bold text-primary text-uppercase">Contact Us</h5>
                <h1 class="mb-0">If You Have Any Query, Feel Free To Contact Us</h1>
            </div>
            <div class="row g-5 mb-5">
                <div class="col-lg-4">
                    <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.1s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-phone-alt text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Call to ask any question</h5>
                            <h4 class="text-primary mb-0">+012 345 6789</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.4s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-envelope-open text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Email to get free quote</h5>
                            <h4 class="text-primary mb-0">info@example.com</h4>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="d-flex align-items-center wow fadeIn" data-wow-delay="0.8s">
                        <div class="bg-primary d-flex align-items-center justify-content-center rounded" style="width: 60px; height: 60px;">
                            <i class="fa fa-map-marker-alt text-white"></i>
                        </div>
                        <div class="ps-4">
                            <h5 class="mb-2">Visit our office</h5>
                            <h4 class="text-primary mb-0">123 Street, NY, USA</h4>
                        </div>
                    </div>
                </div>
            </div>
            {% if messages %}
						{% for message in messages %}
							<div class="alert alert-{{message.tags}}">
								{{message}}
							</div>
						{% endfor %}

					{% endif %}
            <div class="contact-form">
                <h4>Leave A Comment</h4>
                <form action="" method="POST">
                    {% csrf_token %}
                        <div class="row g-5">
                            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.3s">
                                <form>
                                    <div class="row g-3">
                                        <div class="col-md-6">
                                            {{form.name}}
                                        </div>
                                        <div class="col-md-6">
                                            {{form.email}}
                                        </div>
                                        <div class="col-12">
                                            {{form.phone}}
                                        </div>
                                        <div class="col-12">
                                            {{form.message}}
                                        </div>
                                        <div class="col-12">
                                            <button class="btn btn-primary w-100 py-3" type="submit">Send Message</button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                            <div class="col-lg-6 wow slideInUp" data-wow-delay="0.6s">
                                <iframe class="position-relative rounded w-100 h-100"
                                    src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3001156.4288297426!2d-78.01371936852176!3d42.72876761954724!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x4ccc4bf0f123a5a9%3A0xddcfc6c1de189567!2sNew%20York%2C%20USA!5e0!3m2!1sen!2sbd!4v1603794290143!5m2!1sen!2sbd"
                                    frameborder="0" style="min-height: 350px; border:0;" allowfullscreen="" aria-hidden="false"
                                    tabindex="0"></iframe>
                            </div>
                        </div>
            </div>
        </div>
    </div>
    <!-- Contact End -->


{% endblock %}

startup_project/startup_con/templates/partials/_base.html
{% include 'partials/_navbar.html' %}

{% block content %}
  
{% endblock  %}

{% include 'partials/_footer.html' %}

startup_project/startup_con/templates/partials/_footer.html
{% load static %}

    

    <!-- Footer Start -->
    <div class="container-fluid bg-dark text-light mt-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container">
            <div class="row gx-5">
                <div class="col-lg-4 col-md-6 footer-about">
                    <div class="d-flex flex-column align-items-center justify-content-center text-center h-100 bg-primary p-4">
                        <a href="{% url 'index' %}" class="navbar-brand">
                            <h1 class="m-0 text-white"><i class="fa fa-user-tie me-2"></i>Startup</h1>
                        </a>
                        <p class="mt-3 mb-4">Lorem diam sit erat dolor elitr et, diam lorem justo amet clita stet eos sit. Elitr dolor duo lorem, elitr clita ipsum sea. Diam amet erat lorem stet eos. Diam amet et kasd eos duo.</p>
                    </div>
                </div>
                <div class="col-lg-8 col-md-6">
                    <div class="row gx-5">
                        <div class="col-lg-4 col-md-12 pt-5 mb-5">
                            <div class="section-title section-title-sm position-relative pb-3 mb-4">
                                <h3 class="text-light mb-0">Get In Touch</h3>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-geo-alt text-primary me-2"></i>
                                <p class="mb-0">123 Street, New York, USA</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-envelope-open text-primary me-2"></i>
                                <p class="mb-0">info@example.com</p>
                            </div>
                            <div class="d-flex mb-2">
                                <i class="bi bi-telephone text-primary me-2"></i>
                                <p class="mb-0">+012 345 67890</p>
                            </div>
                            <div class="d-flex mt-4">
                                <a class="btn btn-primary btn-square me-2" href="#"><i class="fab fa-twitter fw-normal"></i></a>
                                <a class="btn btn-primary btn-square me-2" href="#"><i class="fab fa-facebook-f fw-normal"></i></a>
                                <a class="btn btn-primary btn-square me-2" href="#"><i class="fab fa-linkedin-in fw-normal"></i></a>
                                <a class="btn btn-primary btn-square" href="#"><i class="fab fa-instagram fw-normal"></i></a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                            <div class="section-title section-title-sm position-relative pb-3 mb-4">
                                <h3 class="text-light mb-0">Quick Links</h3>
                            </div>
                            <div class="link-animated d-flex flex-column justify-content-start">
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                                <a class="text-light" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-12 pt-0 pt-lg-5 mb-5">
                            <div class="section-title section-title-sm position-relative pb-3 mb-4">
                                <h3 class="text-light mb-0">Popular Links</h3>
                            </div>
                            <div class="link-animated d-flex flex-column justify-content-start">
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Home</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>About Us</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Our Services</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Meet The Team</a>
                                <a class="text-light mb-2" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Latest Blog</a>
                                <a class="text-light" href="#"><i class="bi bi-arrow-right text-primary me-2"></i>Contact Us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- Footer End -->


    <!-- Back to Top -->
    <a href="#" class="btn btn-lg btn-primary btn-lg-square rounded back-to-top"><i class="bi bi-arrow-up"></i></a>


    <!-- JavaScript Libraries -->
    <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js"></script>
    <script src="{% static 'lib/wow/wow.min.js' %}"></script>
    <script src="{% static 'lib/easing/easing.min.js' %}"></script>
    <script src="{% static 'lib/waypoints/waypoints.min.js' %}"></script>
    <script src="{% static 'lib/counterup/counterup.min.js' %}"></script>
    <script src="{% static 'lib/owlcarousel/owl.carousel.min.js' %}"></script>

    <!-- Template Javascript -->
    <script src="{% static 'js/main.js' %}"></script>
</body>

</html>

startup_project/startup_con/templates/team.html
{% extends 'partials/_base.html' %}

{% load static %}

{% block content %}
    <!-- Team Start -->
    <div class="container-fluid py-5 wow fadeInUp" data-wow-delay="0.1s">
        <div class="container py-5">
            <div class="section-title text-center position-relative pb-3 mb-5 mx-auto" style="max-width: 600px;">
                <h5 class="fw-bold text-primary text-uppercase">Team Members</h5>
                <h1 class="mb-0">Professional Stuffs Ready to Help Your Business</h1>
            </div>
            <div class="row g-5">
                {%  for tim in team   %}
                <div class="col-lg-4 wow slideInUp" data-wow-delay="0.3s">
                    <div class="team-item bg-light rounded overflow-hidden">
                        <div class="team-img position-relative overflow-hidden">
                            <img class="img-fluid w-100" src="{{tim.image.url}}" alt="">
                            
                            <div class="team-social">
                                {% for socmedia in tim.socmedia_set.all %}
                                    <a class="btn btn-lg btn-primary btn-lg-square rounded"   href="{{ socmedia.link }}"><img class="img-fluid w-48" src="{{socmedia.icon.url}}" alt=""></a>
                                {% endfor %}
                            </div>
                            
                        </div>
                        <div class="text-center py-4">
                            <h4 class="text-primary">{{tim.name}}</h4>
                            <p class="text-uppercase m-0">{{tim.description}}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
    <!-- Team End -->
{% endblock %}